comparedata/urls.py
from django.urls import path

from . import views

urlpatterns = [
    # path('mylist/', views.MyList.as_view(), name='mylist'),
    # path('', views.index, name='index'),    
    path('', views.IndexView.as_view(), name='index'),
    # path('oauth-response', views.IndexView.as_view(), name='oauth_response'),
	path('oauth-response', views.OAuthResponse.as_view(), name='oauth_response'),
    path('loading/<str:job_id>/', views.LoadingPage.as_view(), name='loading_page'), 
    path('load-user-tokens', views.LoadUserTokens, name='load-user-tokens'),
    path('select-object/<str:job_id>/', views.SelectObject.as_view(), name='select_object'),
    path('job-status/<str:job_id>/', views.job_status, name='comparedata.views.job_status'),
    path('get-fields/<str:job_id>/<str:object_id>/', views.get_fields, name = 'comparedata.views.get_fields'),
    path('compare-data/<str:job_id>/<str:object_id>/', views.execute_data_compare, name ='comparedata.views.execute_data_compare'),
    path('compare-data-result/<str:job_id>/', views.CompareDataResult.as_view(), name='compare_data_result'),
    path('unmatched-rows/<str:job_id>/<str:org_no>/', views.get_unmatched_rows, name='comparedata.views.get_unmatched_rows'),
]

sfdatacompare/urls.py
from django.urls import include,path
from django.contrib import admin


urlpatterns = [
    path('',include('comparedata.urls')),
	path('admin', admin.site.urls),
	
]

comparedata/forms.py
from django import forms

class JobForm(forms.Form):
	"""
		Form to handle the creation of a job
	"""
	org_one = forms.CharField(required=True)
	org_two = forms.CharField(required=True)

sfdatacompare/templates/base.html
<!DOCTYPE html>
<html>
	<head>
		<title>Salesforce.com Data Compare Tool</title>
		<meta name="keywords" content="salesforce, salesforce.com, force.com, compare, data, sfdatacompare" />
  		<meta name="description" content="Compare data from objects between two Salesforce Orgs." />
  		<meta name="author" content="Ben Edwards (ben@benedwards.co.nz)" />
  		<meta charset="UTF-8" />

  		{% block css %}{% endblock %}
  		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
		<link rel="stylesheet" type="text/css" href="/static/css/styles.css" />		

		<script>
		  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
		  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
		  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
		  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

		  ga('create', 'UA-18288189-28', 'auto');
		  ga('send', 'pageview');
		</script>
	</head>	

	<body>
	    <div class="modal fade" id="infoModal" tabindex="-1" role="dialog" aria-labelledby="infoModalLabel" aria-hidden="true">
			<div class="modal-dialog small_dialog">
		    	<div class="modal-content">
		      		<div class="modal-header">
		        		<button type="button" class="close" data-dismiss="modal">
		        			<span aria-hidden="true">&times;</span>
		        			<span class="sr-only">Close</span>
		        		</button>
		        		<h3 class="modal-title" id="apiModalLabel">
		        			Salesforce Data Compare
		        		</h3>
		      		</div>
		      		<div class="modal-body">
		        		<p>
		        			For any errors or issues, please feel free to contact me on twitter <a href="https://twitter.com/benedwards44" target="_blank">@benedwards44</a> or via email <a href="mailto:ben@benedwards.co.nz">ben@benedwards.co.nz</a>.
		        		</p>
		        		<p>
		        			I am constantly trying to update and improve this application, as well as other apps I'm working on. Feel free to contact me if you'd like to contribute or have any ideas. All my applications are open sourced on GitHub at <a href="http://github.com/benedwards44" target="_blank">http://github.com/benedwards44</a>.
		        		</p>
		        		<p>
		        			If you haven't already, check out my other apps at the Salesforce Toolkit Page:<br/>
		        			<a href="http://sftoolkit.co/" target="_blank">http://sftoolkit.co/</a>
		        		</p>
		      		</div>
		      		<div class="modal-footer">
				        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
				    </div>
		    	</div>
		  	</div>
		</div>

		<div class="clear"></div>

		<div class="col-md-8 col-md-offset-2">
			{% block content %}{% endblock %}
		</div>

		<!-- JS Scripts -->
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
		<script type="text/javascript" src="/static/js/main.js"></script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

		<!-- Cookie scipt for AJAX posts to controller -->
		<script src="/static/js/cookie.js"></script>
		
		{% block scripts %}{% endblock %}

	</body>

</html>

sfdatacompare/templates/compare_data_result.html
{% extends 'base.html' %}

{% block content %}

	<div class="col-md-6">
		<h1>Salesforce Data Compare</h1>
	</div>

	<div ng-app="compareResultsApp">

		<div ng-controller="CompareResultsController" ng-init="init('{{ job.random_id }}','{{ job.object_id }}','{{ job.fields }}')">

			<div class="col-md-6 text-right">
				<a href="/select-object/{{ job.random_id }}/" class="btn btn-info" style="margin-top: 20px;">
					<span class="glyphicon glyphicon-backward" aria-hidden="true"></span>
					&nbsp; Select Another Object
				</a>
				<a href="#" class="btn btn-warning" style="margin-top: 20px;" ng-click="rerunJob()">
					Rerun &nbsp;
					<span class="glyphicon glyphicon-repeat" aria-hidden="true"></span>
				</a>
			</div>

			<div class="col-md-12">

				<br/>

				<p>
					And the results are in! The information below displays a comparison of the records between the two orgs, for the selected object and the selected fields.
				</p>

				<hr/>

				<table class="table table-hover table-striped">
					<tr>
						<th><h4 class="no-margin">Object</h4></th>
						<td colspan="2">{{ job.object_label }} ({{ job.object_name }})</td>
					</tr>
					<tr>
						<th><h4 class="no-margin">Fields</h4></th>
						<td colspan="2">{{ job.fields }}</td>
					</tr>
				</table>

				<br/>

				<table class="table table-hover table-striped">
					<tr>
						<td></td>
						<th><h4 class="no-margin">{{ job.sorted_orgs.0.username }}</h4></th>
						<th><h4 class="no-margin">{{ job.sorted_orgs.1.username }}</h4></th>
					</tr>
					<tr>
						<th><span data-toggle="tooltip" data-placement="top" title="The number of records that exist in the object"># Records</span></th>
						<td>{{ job.row_count_org_one }}</td>
						<td>{{ job.row_count_org_two }}</td>
					</tr>
					<tr>
						<th><span data-toggle="tooltip" data-placement="top" title="The number of records that exist in one org, and also exists in the other"># Matching Rows</span></th>
						<td>{{ job.matching_rows_count_org_one }}</td>
						<td>{{ job.matching_rows_count_org_two }}</td>
					</tr>
					<tr>
						<th><span data-toggle="tooltip" data-placement="top" title="The number of records that exist in one org, but doesn't exist in the other"># Unmatching Rows</span></th>
						<td>{{ job.unmatching_rows_count_org_one }}</td>
						<td>{{ job.unmatching_rows_count_org_two }}</td>
					</tr>

				</table>

				<hr/>

				{% if job.unmatching_rows_count_org_one > 0 or job.unmatching_rows_count_org_two > 0 %}

					<h2>Unmatched Records</h2>

					<div class="unmatched-records">

						<!-- Nav tabs -->
					  	<ul class="nav nav-tabs" role="tablist">
					    	<li role="presentation" class="active">
					    		<a href="#orgone" aria-controls="orgone" role="tab" data-toggle="tab">
					    			{{ job.sorted_orgs.0.username }}
					    		</a>
					    	</li>
					    	<li role="presentation">
					    		<a href="#orgtwo" aria-controls="orgtwo" role="tab" data-toggle="tab">
					    			{{ job.sorted_orgs.1.username }}
					    		</a>
					    	</li>
					 	</ul>

						<!-- Tab panes -->
						<div class="tab-content">

							<div role="tabpanel" class="tab-pane active padding-10" id="orgone">

								{% if job.unmatching_rows_count_org_one > 0 %}

									{% verbatim %}

									<table class="table table-striped table-hover" id="orgone_table">
										<thead>
											<tr>
												<th ng-repeat="field in fields">{{ field }}</th>
											</tr>
										</thead>
					    				<tbody>
					    					<tr ng-repeat="record in org_one_records">
					    						<td ng-repeat="field in fields">
					    							{{ record[field] }}
					    						</td>
					    					</tr>
					    				</tbody>
									</table>

					    			{% endverbatim %}

								{% else %}

									<div role="alert" class="alert alert-success">
										There are no unmatched records for this Org.
									</div>

								{% endif %}

							</div>

					    	<div role="tabpanel" class="tab-pane padding-10" id="orgtwo">

					    		{% if job.unmatching_rows_count_org_two > 0 %}

					    			{% verbatim %}

									<table class="table table-striped table-hover" id="orgone_table">
										<thead>
											<tr>
												<th ng-repeat="field in fields">{{ field }}</th>
											</tr>
										</thead>
					    				<tbody>
					    					<tr ng-repeat="record in org_two_records">
					    						<td ng-repeat="field in fields">
					    							{{ record[field] }}
					    						</td>
					    					</tr>
					    				</tbody>
									</table>

					    			{% endverbatim %}
					    
								{% else %}

									<div role="alert" class="alert alert-success">
										There are no unmatched records for this Org.
									</div>

								{% endif %}
					    	
				    		</div>

					  	</div>

					</div>

				{% else %}

					<div role="alert" class="alert alert-success">
						Congrats! It looks like all your data is matching.
					</div>

				{% endif %}

				<br/><br/><br/><br/>

			</div>

		</div>

	</div>

{% endblock %}

{% block scripts %}

	<!-- Angular scripts -->
	<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular.min.js"></script>	
	<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular-route.min.js"></script>	
	<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular-resource.min.js"></script>

	<!-- Angular controller -->
	<script src="/static/js/compare-data-results-controller.js"></script>

{% endblock %}

sfdatacompare/templates/index.html
{% extends 'base.html' %}

{% block content %}

	<h1>Salesforce Data Compare</h1>
	<p>
		This tool uses the Salesforce REST API to query objects in your databases and compare data between two Orgs. This is useful for post-data migrations to ensure that the data is migrated successfully and all rows match. It also allows for reference tables and custom settings to be matched and managed.
	</p>
	<p>
		None of your organisation information or data is captured or kept from running this tool. Because this tool is querying data in your Salesforce Org, if you are running on behalf of a client or do not own the data, it is important to ensure people are aware that another cloud-based tool is accessing your Salesforce data.
	</p>
	<p>
		Note: You will need to be a System Administrator on both Orgs in order to use this application.
	</p>

	{% verbatim %}
	<div ng-app="selectOrgApp">
		<div ng-controller="SelectOrgController" ng-init="init()">
			<div class="left-half">

				<h2>Org One</h2>

				<table id="orgOneLogin">

					<tr>
						<td width="125">
							<select id="org_one_env" name="org_one_env" class="form-control">
								<option value="Production">Production</option>
								<option value="Sandbox">Sandbox</option>
							</select>
						</td>
						<td>
							&nbsp;&nbsp;
							<button type="button" id="orgOneButton">
								Login
							</button>
						</td>
					</tr>

				</table>

				<table id="orgOneDisplay" style="display:none;">

					<tr>
						<td width="90">
							<strong>Username</strong>
						</td>
						<td>
							<span id="orgOneUsername"></span>
						</td>
					</tr>

					<tr>
						<td>
							<strong>Org</strong>
						</td>
						<td>
							<span id="orgOneOrg"></span>
						</td>
					</tr>

				</table>
				<br>
				<h2>Org One</h2>
				<br>	
				<div class="col-md-6">
					<select class="form-control" id="org-select-1" ng-model="userName1">
						<option ng-repeat ="token in all_tokens" value="{{token.username }}"> {{token.username }} - {{token.org_name}}</option>
					</select>
				</div>

			</div>

			<div class="right-half">

				<h2>Org Two</h2>

				<table id="orgTwoLogin">

					<tr>
						<td width="125">
							<select id="org_two_env" name="org_two_env" class="form-control">
								<option value="Production">Production</option>
								<option value="Sandbox">Sandbox</option>
							</select>
						</td>
						<td>
							&nbsp;&nbsp;
							<button type="button" id="orgTwoButton">
									Login
							</button>
						</td>
					</tr>

				</table>

				<table id="orgTwoDisplay" style="display:none;">

					<tr>
						<td width="90">
							<strong>Username</strong>
						</td>
						<td>
							<span id="orgTwoUsername"></span>
						</td>
					</tr>

					<tr>
						<td>
							<strong>Org</strong>
						</td>
						<td>
							<span id="orgTwoOrg"></span>
						</td>
					</tr>

				</table>
				<br>
				<h2>Org Two</h2>
				<br>	
				<div class="col-md-6">
						<select class="form-control" id="org-select-2" ng-model="userName2">
							<option ng-repeat ="token in all_tokens" value="{{token.username }}"> {{token.username }} - {{token.org_name}}</option>
						</select>
					</div>
			</div>
	

	{% endverbatim %}
	<div class="clear"></div>

	<div id="compareOrgs">

		<form action="." method="POST">

			{% csrf_token %}

			<div style="clear:both;margin: 5px 0;"></div>

			<input type="hidden" id="client_id" value="{{ client_id }}" />
			<input type="hidden" id="redirect_uri" value="{{ redirect_uri }}" />
			{% verbatim %}
			<input type="hidden" id="id_org_one" name="org_one" ng-value="userName1"/>
			<input type="hidden" id="id_org_two" name="org_two" ng-value="userName2"/>
			{% endverbatim %}
			<input type="submit" value="Begin Compare" />

		</form>

	</div>

</div>
</div>	

	{% if form.errors %}

		<div class="alert alert-danger" role="alert">
			{{ form.errors }}
		</div>

	{% endif %}

	<!-- Force logout when page is loaded -->
	<iframe src="https://login.salesforce.com/secur/logout.jsp" width="0" height="0" style="display:none;"></iframe>
    <iframe src="https://test.salesforce.com/secur/logout.jsp" width="0" height="0" style="display:none;"></iframe>

{% endblock %}


{% block scripts %}

	<!-- Angular scripts -->
	<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular.min.js"></script>	
	<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular-route.min.js"></script>	
	<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular-resource.min.js"></script>

	<!-- Angular controller -->
	<script src="/static/js/select-org-controller.js"></script>

{% endblock %}

sfdatacompare/templates/loading.html
{% extends 'base.html' %}

{% block content %}

	<h1>Salesforce Data Compare</h1>

	{% if job.status == 'Downloading Objects' %}
		<p>
			This tool uses the Salesforce REST API to query objects in your databases and compare data between two Orgs. This is useful for post-data migrations to ensure that the data is migrated successfully and all rows match. It also allows for reference tables and custom settings to be matched and managed.
		</p>
		<p>
			None of your organisation information or data is captured or kept from running this tool. Because this tool is querying data in your Salesforce Org, if you are running on behalf of a client or do not own the data, it is important to ensure people are aware that another cloud-based tool is accessing your Salesforce data.
		</p>
		<p>
			Note: You will need to be a System Administrator on both Orgs in order to use this application.
		</p>
	{% endif %}
	
	<div class="loading-components">

		<br/><br/>

		<div style="float:left;">
			<img src="/static/images/loading.gif" alt="Loading" title="Loading" />
		</div>

		<div style="float:left;margin-left:20px;">
			<h1 style="font-size:1.5em;margin-top:20px;">
				{% if job.status == 'Downloading Objects' %}
					Querying your objects...
				{% else %}
					Comparing your data...
				{% endif %}
			</h1>
			<p>
				{% if job.status == 'Downloading Objects' %}
					Time on this will vary depending on the number of objects in your Org.
				{% else %}
					Time on this will vary depending on the size of data and number of fields in your selected object.
				{% endif %}
			</p>
		</div>

	</div>

	<div class="alert alert-danger error" role="alert" style="display:none;">
		<p>
			There was an error processing your request: <i class="error_message"></i>
			<br/><br/>
			Please <a href="/">return</a> to the home page and try again.
		</p>
	</div>

	<script>
 		window.setInterval(function () 
 		{
       		$.ajax({
			    url: '/job-status/{{ job.random_id }}',
			    type: 'get', 
			    dataType: 'json',
			    success: function(resp) 
			    {
			    	if (resp.status == 'Objects Downloaded') 
			    	{
			    		window.location = '/select-object/{{ job.random_id }}/';
			    	}
			        else if (resp.status == 'Finished')
			        {
			        	window.location = '/compare-data-result/{{ job.random_id }}/';
			        } 
			        else if (resp.status == 'Error')
			        {
			        	$('.loading-components').hide();
			        	$('.error').show();
			        	$('.error_message').text(resp.error);
			        }
			        // Else job is still running, this will re-run shortly.
			    },
			    failure: function(resp) 
			    { 
			        $('.loading-components').hide();
		        	$('.error').show();
		        	$('.error_message').text(resp);
			    }
			});
    	}, 1000);
	</script>

{% endblock %}

sfdatacompare/templates/logout.html
{% extends 'base.html' %}

{% block content %}

	<h1>Salesforce Org Data Comparer</h1>
	<p>
		Successfully logged out of Salesforce and Package Builder
	</p>

	<iframe src="https://login.salesforce.com/secur/logout.jsp" width="0" height="0" style="display:none;"></iframe>
	<iframe src="https://test.salesforce.com/secur/logout.jsp" width="0" height="0" style="display:none;"></iframe>

	<script>
		setTimeout(function () {
       		window.location.href = "/";
    	}, 3000);
	</script>

{% endblock %}

sfdatacompare/templates/oauth_response.html
<!DOCTYPE html>
<html>

	<head>
		<title>Salesforce.com Data Compare Tool</title>
		<meta name="keywords" content="salesforce, salesforce.com, force.com, compare, data, sfdatacompare" />
  		<meta name="description" content="Compare data from objects between two Salesforce Orgs." />
  		<meta name="author" content="Ben Edwards (ben@benedwards.co.nz)" />
  		<meta charset="UTF-8" />

  		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
		<link rel="stylesheet" type="text/css" href="/static/css/styles.css" />
		
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
		<script type="text/javascript" src="/static/js/main.js"></script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
  	</head>

  	<body>

        <div style="padding:20px 40px;">

      		{% if error %}

                <h2>Error</h2>

  			    <div class="alert alert-danger" role="alert">
                    There was an error authorising your login:<br/>
                    <strong>{{ error_message }}</strong>
                    <br/><br/>
                    Please close this window and try again.
                </div>

                <button onclick="window.close();">Close</button>

      		{% else %}

                <h2>Success</h2>

                <div class="alert alert-success" role="alert">
                    Your authorisation has been successful. Please wait while your details are loaded.
                </div>

                <button onclick="window.close();">Close</button>

      			<script>
      				window.opener.updateOrgDetails(
      					'{{ org_choice }}',
      					'{{ username }}', 
      					'{{ org_name }}', 
      					'{{ org.id }}', 
      					'{{ email }}'
      				);

                    setTimeout(function() {
                        window.close();
                    },
                        2000
                    );
      			</script>

      		{% endif %}

            <iframe src="https://login.salesforce.com/secur/logout.jsp" width="0" height="0" style="display:none;"></iframe>
            <iframe src="https://test.salesforce.com/secur/logout.jsp" width="0" height="0" style="display:none;"></iframe>
            <iframe src="{{ instance_url }}/secur/logout.jsp" width="0" height="0" style="display:none;"></iframe>

        </div>

  	</body>

</html>

sfdatacompare/templates/select_object.html
{% extends 'base.html' %}

{% block content %}

	<h1>Salesforce Data Compare</h1>

	<p>
		Select an object from the list below and then tick the fields you want to use to compare the data to. It is recommended to only select fields that aren't unique to an Org. Eg. Id and auto-number fields.
	</p>
	<p>
		Note: This will only show objects and fields that exist in both environments.
	</p>

	<hr />

	<div ng-app="selectObjectsApp">

		<div ng-controller="SelectObjectsController" ng-init="init('{{ job.random_id }}')">
			<div class="col-md-3">
				<h2 class="no-margin">Select Object</h2>
			</div>
			<div class="col-md-6">
				<select class="form-control" id="object-select" ng-model="objectId" ng-change="objectChange()">
					<option value="">-- Select Option --</option>
					{% for object in job.sorted_objects %}
						<option value="{{ object.id }}">{{ object.label }} ({{ object.api_name }})</option>
					{% endfor %}
				</select>
			</div>

			<div class="col-md-12" id="field-select">

				<br/><br/>

				{% verbatim %}

				<div class="col-md-12">

					<div class="col-md-6">
						<h3 class="no-margin">Select Fields</h3>
					</div>

					<div class="col-md-6 text-right">
						<button class="btn btn-success" ng-click="compareData()">
							Compare Data &nbsp;&nbsp; 
							<span class="glyphicon glyphicon-play"></span>
						</button>
					</div>

					<div class="col-md-12">

						<hr/>

						<table class="table table-hover table-striped" id="fields_table">

					    	<thead>
					    		<tr>
					    			<th width="1%">
										<input type="checkbox" ng-model="checkAll" ng-change="checkAllChange()" />
									</th>
						    		<th>Label</th>
						    		<th>API Name</th>
						    		<th>Type</th>
						    	</tr>
					    	</thead>

					    	<tbody>

					    		<tr ng-repeat="field in fields">

					    			<td>
					    				<input type="checkbox" ng-model="field.checked" />
					    			</td>
					    			<td>{{ field.label }}</td>
					    			<td>{{ field.api_name }}</td>
					    			<td>{{ field.type }}</td>
					    		</tr>

					    	</tbody>

					    </table>

					</div>

				</div>

			    {% endverbatim %}

			</div>

		</div>

	</div>

	<div class="modal fade" id="progressModal" tabindex="-1" role="dialog" aria-labelledby="progressModalLabel" aria-hidden="true">
		<div class="modal-dialog">
	    	<div class="modal-content">
	      		<div class="modal-header"></div>
	      		<div class="modal-body"></div>
	      		<div class="modal-footer"></div>
	    	</div>
	  	</div>
	</div>

{% endblock %}

{% block scripts %}

	<!-- Angular scripts -->
	<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular.min.js"></script>	
	<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular-route.min.js"></script>	
	<script src="https://ajax.googleapis.com/ajax/libs/angularjs/1.3.14/angular-resource.min.js"></script>

	<!-- Angular controller -->
	<script src="/static/js/select-object-controller.js"></script>

{% endblock %}

sfdatacompare/templates/test.html
<head>
	<meta http-equiv="content-type" content="text/html;charset=utf-8" />
	<title>框总结</title>
</head>

<body>
<br />	
	<li>
	<label>下拉框</label>
	<select >
		<option>-请选择-</option>
		<option>1</option>
		<option>2</option>
	</select>
	</li>	
<br />
	<li>
	<label>单选框</label><br/>
	<input name="radiobutton" type="radio" value="男" checked="checked"/>男<br/>
	<input name="radiobutton" type="radio" value="女" checked="checked"/>女
	</li>
    
    <li>
        <label>单选框</label><br/>
        <input name="radiobutton" type="radio" value="男" checked="checked"/>男<br/>
        <input name="radiobutton" type="radio" value="女" checked="checked"/>女
        </li>
<br />
	<li>
	<label>多选框</label><br/>
	<input name="radiobutton" type="checkbox" value="篮球" checked="checked"/>篮球<br/>
	<input name="radiobutton" type="checkbox" value="足球" checked="checked"/>足球<br/>
	<input name="radiobutton" type="checkbox" value="排球" checked="checked"/>排球
	</li>
	
<br />
	<li>
	<label>table表格</label><br/>
	<table border="1">
		<tr>
			<td>地区</td>
			<td>日期</td>
		</tr>
	</table>
	</li>
	
	<br />
	<li>
	<label>form表单</label><br/>
	<form action="" method="get"> 
	性别：<br /> 
	<input name="sex" id="man" type="radio" value="" /> 
	<label for="man">男</label> 
	<input name="sex" id="woman" type="radio" value="" /> 
	<label for="woman">女</label> 
	</form>
    </li>
    
    <form>
        <select name="xueli" id="" >
        <option value="初中">初中</option>
        <option value="高中">高中</option>
        <option value="大学" selected="selected">大学</option>
        </select>
        </form>
</body>